### ISSUE TITLE
icon/logo

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#1]
update icon/logo in top left header.

**Comment by kekoziar** [comment]
Updated to temporary logos:
https://github.com/uc-love-data-week/uc-love-data-week.github.io/commit/bf21219824b207859533e3abf302b307bb408ac1
https://github.com/uc-love-data-week/uc-love-data-week.github.io/commit/1cc74acb1b6420780a314b603956a210f80342b2

**Comment by kekoziar** [comment]
We need an inverted color logo w/transparent background.

**Comment by U2NG** [comment]
I noticed the big heart logo is missing UCSF. I've mentioned it to Erinna, my student asst., and she is working on an update.

**Comment by U2NG** [comment]
i added an image title ldw-circuit-color.png to the assets folder.  this is the final heart circuit logo.  there is a white version and black version

**Comment by kekoziar** [comment]
added transparent version.
