### ISSUE TITLE
Participating Campuses

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#11]
Gather and add logos for participating campuses/organizations/offices/etc.

**Comment by kristi-sara** [comment]
I'm assuming they would be added to the assets/img folder?

**Comment by kekoziar** [comment]
@kristi-sara  Yes. We can make a subfolder so it doesn't get terribly cluttered.

**Comment by kekoziar** [comment]
finished.
