### ISSUE TITLE
Open external link as new tab

### ISSUE THREAD

**Issue by rcurty** [uc-love-data-week/uc-love-data-week.github.io#130]
Consider changing the external link to open as a new tab: [create their own fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)

https://github.com/uc-love-data-week/uc-love-data-week.github.io/wiki

**Comment by stephlabou** [comment]
Documenting in case this comes up again - this is possible, but need to use HTML, not regular markdown syntax.

References:
https://stackoverflow.com/questions/4425198/can-i-create-links-with-target-blank-in-markdown
