### ISSUE TITLE
Stage 2025 site

### ISSUE THREAD

**Issue by stephlabou** [uc-love-data-week/uc-love-data-week.github.io#136]
[Documentation](https://github.com/uc-love-data-week/uc-love-data-week.github.io/wiki/Create-and-stage-new-year)

**Comment by stephlabou** [comment]
@wdahdul will do amazing at this

**Comment by stephlabou** [comment]
Update wiki documentation to clarify index.html and staging layout file

**Comment by wdahdul** [comment]
I updated the [documentation](https://github.com/uc-love-data-week/uc-love-data-week.github.io/wiki/Create-and-stage-new-year) with details about index.html and layout file
