### ISSUE TITLE
Render bulletpoints in descriptions

### ISSUE THREAD

**Issue by wdahdul** [uc-love-data-week/uc-love-data-week.github.io#140]
Bulletpoint lists in descriptions are collapsed into the block of text when rendered on the website. For example:   
https://uc-love-data-week.github.io/#openresearch
Is there a way to format to the text for correct rendering?

**Comment by stephlabou** [comment]
Adding to this that the pop up text URL doesn't resolve to the actual pop up. Something like [https://uc-love-data-week.github.io/#openresearch](https://uc-love-data-week.github.io/#openresearch) resolves to the main home page the same as the main website URL [https://uc-love-data-week.github.io/](https://uc-love-data-week.github.io) would resolve

**Comment by stephlabou** [comment]
@kekoziar I haven't been able to figure the bit about the URL with # not resolving to the pop, could use your help at some point.

**Comment by stephlabou** [comment]
The # in URL is just the way it is

**Comment by stephlabou** [comment]
@kekoziar will look into the bullets not rendering properly

**Comment by kekoziar** [comment]
bullet points need to be coded in html within the description in order to render.
