### ISSUE TITLE
UC Merced's workshop description is showing up on UCSB event

### ISSUE THREAD

**Issue by kristi-sara** [uc-love-data-week/uc-love-data-week.github.io#17]
Renata noticed that when you click on 'Webscraping using Xpath on Chrome', the description of UC Merced's 'Webscraping in R' workshop comes up instead. I took a look at  _data/yml_2021/workshops.yml but the correct information for both workshops  is there. I'm not sure why Merced's event is showing up under UCSB's.

**Comment by kekoziar** [comment]
In the `workshops.yml` file, `name` value needs to be unique.  I changed the values to `webscraping-ucm` and `webscraping-ucsb` so the info is pulled from the correct ones.

**Comment by kristi-sara** [comment]
Thanks Kat!
