### ISSUE TITLE
Update 2022 Website

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#19]
During a committee/website group meeting, we agreed on the following changes

Remove content that is too hidden
- [x] About section
- [x] Don’t need speakers listed. 

Add to Header
- [x] Link to Slack
- [x] submenu: Workshop: Calendar: workshop info; slack

Preservation
- [x] Create `2021` subfolder which will link to last year's content
- [x] re-force capture by wayback machine

Calendar
- [x] Current elements: Title, time, registration link.
- [x] Check UC brand colors for colorblind accessibility
- [x] Add legend
- [ ] After event, remove _time_ & _registration link_ and add _recording_ and _slides_

Analytics
- [ ] Check google analytics

**Comment by kekoziar** [comment]
- [ ] re-add link to campus contacts in main header.

@U2NG, @arieldeardorff should the link be by itself or nested under a Contact Us menu with Slack?  I'm leaning toward the latter, but am worried the Slack channel might get lost.

**Comment by arieldeardorff** [comment]
I could go either way. I lean towards nesting them under Contact Us but I didn't really use the Slack channel last year. If we think lots of folks will be using it during their sessions and throughout the week then maybe it should be a top level...

**Comment by kekoziar** [comment]
What if we use a different header.  _Connect_ ?  Something else that encompasses both?

**Comment by arieldeardorff** [comment]
Yes! "Connect" is a great idea!

**Comment by U2NG** [comment]
I agree "Connect" is a great choice.  Thanks Kat!
