### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#22]
More support documentation is needed so others can assist.  The wiki needs to be updated with

- [x] How to render it locally (Windows & macOS)
- [x] Overview of how the website is organized
- [x] Walkthrough of how a file is populated

**Comment by kekoziar** [comment]
see also #30

**Comment by stephlabou** [comment]
@wdahdul

**Comment by stephlabou** [comment]
Same as more detailed in [#30](https://github.com/uc-love-data-week/uc-love-data-week.github.io/issues/30)
