### ISSUE TITLE
Dropdown menu background colors

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#24]
It would be nice if the background colors of the dropdown menu match the header bg color (or transparency) directly.  I think the code for that is somewhere in bootstrap.

**Comment by devnich** [comment]
I may have inadvertently fixed this as part of the front page layout. If not, I know where to find the code, let me know.

**Comment by kekoziar** [comment]
the new layout added in #38 removes the transparency of the header, so this, in effect, is fixed. Thanks @devnich!!
