### ISSUE TITLE
Update 2023 Website layout

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#29]
During a committee/website group meeting, we agreed on the following changes.  

Update layout of main page
- [x] Remove main graphic, and redesign with <3 and blurb
- [x] Add calendar directly below

Add to Header
- [x] Move Calendar link so it's top level on menu/header
- [x] Workshops top level menu item links to workshop info

Calendar
- [x] Add modal popup to info links in calendar

Preservation
- [x] Update header menu link so 2022 links to subfolder
- [x] Double-check subfolder content links properly
- [x] Create `2023` subfolder which will link to this year's content
- [x] re-force capture by wayback machine

Analytics
- [ ] Check google analytics

Discussed during Dec 2 meeting
Responsive design
- [x] hide calendar and allow (dynamically created) list/table view on mobile
- [ ] nice to have: button to switch between calendar and list view

**Comment by stephlabou** [comment]
Attempting calendar move, 11/14

**Comment by stephlabou** [comment]
To archive content:

In YYYY_pages, update permalink to be YYYY/[item] rather than permalinked to main [item]

**Comment by kekoziar** [comment]
I'm working on moving the calendar javascript content into an includes file, but won't update until #36 is merged.

**Comment by kekoziar** [comment]
> Claiming 2 items under "Update layout of main page"

@devnich I already moved the calendar, but forgot to click the checkbox.  You can see how it looks on the [index_dev.html](http://uc-love-data-week.github.io/2023/index_dev.html) page, which I added so we wouldn't have to continuously comment/uncomment while developing.

**Comment by devnich** [comment]
I'm claiming 2 "Add to Header" items

**Comment by kekoziar** [comment]
Claimed modal during meeting.  implemented w/#41.

**Comment by kekoziar** [comment]
updated task list with content discussed during Friday's meeting.

**Comment by stephlabou** [comment]
PR #47 handles calendar on mobile (small screens)
