### ISSUE TITLE
Update 2023 content

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#32]
I think this is everything.  We can do the first two tasks easily. Email requests for the next two, or ask at CKG/UCDLW meetings. But, the last three are contingent on getting info from the spreadsheet. 

Update 2023 Content
- [x] Make copy of `yml_2022` folder to `yml_2023`
- [x] Update `dates.yml`
- [x] Verify/update campus/org contacts: `contacts.yml`
- [x] Verify/update campus/org logos: `/assets/img/campuses/`
- [x] Workshop info reminders & followup requests
- [x] Verify/update campuses.yml with sponsors of workshops: `campuses.yml`
- [x] update `workshop.yml`
- [x] update workshop specific logos: `/assets/img/workshops/` & `workshop.yml`

**Comment by stephlabou** [comment]
Working on sub-issues 1-4 on 2022-11-02

**Comment by stephlabou** [comment]
Claiming updating workshop.yml and updating workshop logos

**Comment by stephlabou** [comment]
PR #45 updates workshop.yml and starts updating workshop specific logos

**Comment by nfultz** [comment]
Is the R User group on Wed (per website) or Thur?

Just got an email that says:

```
R Users Group Cross-UC Meetup
Feb. 16, 2023, 10 a.m. - Feb. 16, 2023, noon
Organizer - DataLab: Data Science and Informatics
Zoom
Contact - [datalab-training@ucdavis.edu](mailto:datalab-training@ucdavis.edu)
```
