### ISSUE TITLE
searchable materials list

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#56]
requested is a searchable materials list

- another example: https://airtable.com/shriK9ydFtWJwqm6e/tblq9LCcYhmRBpTAj

**Comment by stephlabou** [comment]
You beat me to it!

Adding use case: a way to see at a glance - and search within - all UC Love Data Week events from past years, with links to materials. Serves as central 'go to' place for all event recordings and slide decks.

**Comment by kekoziar** [comment]
@stephlabou you added more meaningful details!

**Comment by stephlabou** [comment]
Option: instead of archiving, put all annual yml data files into one searchable thing

**Comment by devnich** [comment]
I'm investigating the possibility of serializing everything to one XML document. That would make the info searchable/scrapable without needing to create additional pages or page stylings.

**Comment by devnich** [comment]
#69 Solves the machine-readable portion of this issue.

**Comment by kekoziar** [comment]
#75 adds the search page.

**Comment by kekoziar** [comment]
search button doesn't work: add on-submit functionality
