### ISSUE TITLE
#/workshop link on home page isn't working

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#64]
The link to jump to the workshop section of the page for the index isn't working.  There are two `section id="workshops"` on the page, which breaks the link. 

`_layouts/2023_home.html` has 
both 
`{% include 2023_includes/workshops-list.html %}`
and
`{% include 2023_includes/workshops.html %}`

which both have `section id="workshops"`

**Comment by kekoziar** [comment]
reopen, still needs fixing

**Comment by devnich** [comment]
Merged PR
