### ISSUE TITLE
Update 2024 content

### ISSUE THREAD

**Issue by wdahdul** [uc-love-data-week/uc-love-data-week.github.io#65]
- [x] Make copy of `yml_2023` folder to `yml_2024`
- [x] Update `dates.yml`
- [x] Verify/update campus/org contacts: `contacts.yml`
- [x] Verify/update campus/org logos: `/assets/img/campuses/`
- [x] Workshop info reminders & followup requests
- [x] Verify/update campuses.yml with sponsors of workshops: `campuses.yml`
- [x] update `workshop.yml`
- [x] update workshop specific logos: `/assets/img/workshops/` & `workshop.yml`

Updates to web 
- [x] add Agenda to header (see 2021 website)
- [x] add back Calendar to header (see 2023 website)

Please comment to claim tasks. The last three items are contingent on getting info from the spreadsheet.

**Comment by stephlabou** [comment]
Web meeting 2023-12-05

@devnich has created xml and json for historical yml data. You can browse the feeds at: <site>/feeds/workshops.xml and <site>/feeds/workshops.json
@kekoziar will work on RSS feed / finding interface by 2024-01-03
@wdahdul will work on adding getting started documentation to [wiki](https://github.com/uc-love-data-week/uc-love-data-week.github.io/wiki) (see also [documentation issue](https://github.com/uc-love-data-week/uc-love-data-week.github.io/issues/30))
@stephlabou will work on re-adding agenda and calendar pages to main page header

**Comment by stephlabou** [comment]
2024 site is live
