### ISSUE TITLE
2023 header

### ISSUE THREAD

**Issue by kekoziar** [uc-love-data-week/uc-love-data-week.github.io#67]
need to add `current` link to 2023 header, which links to current workshops/site

**Comment by stephlabou** [comment]
And add to 2024 header

**Comment by stephlabou** [comment]
@kekoziar clicking on "UC Love Data Week" on the banner sends back to current. Sufficient, or add a new button on header?

**Comment by stephlabou** [comment]
@kekoziar addressed by [PR #134 ](https://github.com/uc-love-data-week/uc-love-data-week.github.io/pull/134)
